theme: jekyll-theme-architect

title: 我不开心
description: I am not happy

ios: https://itunes.apple.com/cn/app/id1197141213
android: http://on9882yfn.bkt.clouddn.com/NotHappy_v1.apk

show_downloads: true